openapi: 3.0.1
info:
  title: Conversation History Plugin
  description: A plugin that allows ChatGPT to retrieve and reference past conversation history.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /history:
    get:
      operationId: history
      summary: Get the conversation history
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  history:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: The unique ID of the message.
                        author_role:
                          type: string
                          description: The role of the author (e.g., "user" or "assistant").
                        text:
                          type: string
                          description: The text content of the message.
        "404":
          description: History not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message.
